name: ci

on:
  push:
    branches-ignore: ["ci"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      # - uses: chipsalliance/verible-linter-action@main
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix-shell --run make:cpu
      - if: contains(github.ref, 'main')
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git add -f src/cpu/obj_dir
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:ci -f